### PR TITLE
Fix escaping filter_key in prometheus output

### LINKED ISSUE #142: Invalid UTF-8 label -- Prometheus Error with VTS Exporter.
Prometheus Version : v2.4.3
Error message :
`
error while linting: text format parsing error in line 501: invalid label value "\xfftest-api"`

Problem information:

We are having 10 nginx servers with VTS module enabled. Somehow the client is making the wrong http request and nginx is throwing 502 error. In this scenario VTS is capturing the invalid character as well.

Prometheus is collecting the metrics from all nginx servers. So if someone hit the nginx with invalid http host then prometheus is scraping all the metrics even with invalid character. This is causing potential failure at prometheus layer.

Its throwing the error:
`error while linting: text format parsing error in line 501: invalid label value "\xfftest-api"
`
We do have three different layers here Nginx , VTS module and Prometheus. Because of this we are potentially loosing our all metrics.

Is there any solution to have on these? Anyway we can tell the prometheus to remove the metric with invalid label and start functioning as usual . I think prometheus somehow should ignore these kind of metric to be logged in prometheus to avoid the failure of prometheus itself.

### PR DESCRIPTION
**Pull request by u5surf**
* Fixes #142
* it can be escaped the 2 - 4 bytes character
in detail, please read below.

https://github.com/vozlt/nginx-module-vts/issues/142#issuecomment-1431427669

### CODE REVIEW

**Review by vozlt — APPROVED** [review]
I'll trust you and leave it to you. The _ngx_http_vhost_traffic_status_escape_prometheus()_ function has been merged from [this PR](https://github.com/vozlt/nginx-module-vts/commit/ead62a0caf405731c88ac138c4c0a82bb316cc18).

**Comment by u5surf** [comment]
@jongiddy Hi, I heard you implement this function, please you could review on this patch🙏

**Review by jongiddy — COMMENTED** [review]
The [Prometheus exposition format](ttps://prometheus.io/docs/instrumenting/exposition_formats/) is UTF-8 encoded so valid UTF-8 characters do not need to be encoded further.

Encoding valid UTF-8 characters to percent-encoding would be surprising. Why did you choose this encoding? The format does not mention this form of escape.

There are 2 problems here:
1. `\xff` is an invalid UTF-8 character but `ngx_utf8_decode` does not detect this.
2. Even if did detect it was invalid, and it tried to use the `\xff` encoding that it uses for `dec > 0x10ffff` that encoding is [not supported](https://github.com/prometheus/common/blob/ca1f99be33b31b804a85a42cb7d3a1df23500bf8/expfmt/text_parse.go#L642).

I would suggest a fix to [ngx_utf8_decode](https://github.com/nginx/nginx/blob/2485681308bd8d3108da31546cb91bb97813a3fb/src/core/ngx_string.c#L1360) to detect more invalid UTF-8 characters, including `\xff`. This allows valid UTF-8 to continue to be sent literally.

Change the handling of invalid UTF-8 to do something other than `\x..`. Maybe percent-encoding is the best we can do.

**Comment by u5surf** [comment]
@jongiddy
> I would suggest a fix to [ngx_utf8_decode](https://github.com/nginx/nginx/blob/2485681308bd8d3108da31546cb91bb97813a3fb/src/core/ngx_string.c#L1360) to detect more invalid UTF-8 characters,

I agree with your suggestion. Right away I send the patch to nginx-devel team.
https://mailman.nginx.org/pipermail/nginx-devel/2023-February/34K6WOSI5JSIRESP32TY73EIIUHATOM5.html

After patch merged. to follow backwards compatibility, we suppose to prepare the branches between versions sometime soon.

**Comment by jongiddy** [comment]
Great. Thanks for creating the nginx patch.

Also, I retract problem 2 in my comment above. My initial reading was that it would replace an invalid character with `\xff` in the exposition format, which Prometheus does not recognize.

Taking a second look, it sends two backslashes (`\\xff`) which is valid in the exposition format and the final text shown to users will be `\xfftest-api`.

Maybe `%FFtest-api` would have been better. It would allow the code to allocate 3 bytes instead of 5 for the remaining characters. But I'm not sure it is worth changing behavior that someone might be expecting.

**Comment by u5surf** [comment]
> Maybe %FFtest-api would have been better. It would allow the code to allocate 3 bytes instead of 5 for the remaining characters. But I'm not sure it is worth changing behavior that someone might be expecting.

@jongiddy 
I consider that your opinion is true in this aspect, but @axingblog @topicgit had said that the below behavior is not expecting   because it can be occurred the invalid format error in promethes(https://github.com/vozlt/nginx-module-vts/issues/142#issuecomment-1278651670). I don't see wether it is true or not, once I heard to them what is happened but none of response from them(https://github.com/vozlt/nginx-module-vts/issues/142#issuecomment-1430555279). Thus they seem to hope that their character get to be  encoding something expression format. So I choice the percent encoding which is adopted generally in RFC 2396 https://www.ietf.org/rfc/rfc2396.txt
Also I was hearing in these points, but they had not any response yet(https://github.com/vozlt/nginx-module-vts/issues/142#issuecomment-1431438908).

**Comment by u5surf** [comment]
@jongiddy 
The nginx patch has merged and I consider that it may release next versions!
https://github.com/nginx/nginx/commit/2c5fccd4693c0a68e1c72d65e016ba83e861120e
For compatibility, We consider that it should return as an invalid character which starts with above 0xf8 following modified nginx decode rules. I changed this patch such that. Can you check it?

File: src/ngx_http_vhost_traffic_status_string.c [hunk 1]
```diff
@@ -187,7 +187,7 @@ ngx_http_vhost_traffic_status_escape_prometheus(ngx_pool_t *pool, ngx_str_t *buf
             }
         } else {
             char_end = pa;
-            if (ngx_utf8_decode(&char_end, last - pa) > 0x10ffff) {
+            if (*char_end > 0xf8 || ngx_utf8_decode(&char_end, last - pa) > 0x10ffff) {
```
Comment (jongiddy) [inline src/ngx_http_vhost_traffic_status_string.c:190]:
```suggestion
            if (*pa >= 0xf8 || ngx_utf8_decode(&char_end, last - pa) > 0x10ffff) {
```
This is a good approach, but `0xf8` is invalid too, so you need to use `>=`.

I also suggest using `*pa` as this is the pointer to the current character. `char_end` happens to have the same value, but it has a different meaning associated with its use in the `ngx_utf8_decode` function.

File: src/ngx_http_vhost_traffic_status_string.c [hunk 2]
```diff
@@ -237,7 +237,7 @@ ngx_http_vhost_traffic_status_escape_prometheus(ngx_pool_t *pool, ngx_str_t *buf
...
```
Comment (jongiddy) [inline src/ngx_http_vhost_traffic_status_string.c:240]: Same as above.

File: src/ngx_http_vhost_traffic_status_string.c (hunk 1 above)
Comment (u5surf) [reply src/ngx_http_vhost_traffic_status_string.c]: @jongiddy Thanks! I fixed it.

File: src/ngx_http_vhost_traffic_status_string.c (hunk 2 above)
Comment (u5surf) [reply src/ngx_http_vhost_traffic_status_string.c]: @jongiddy Also fixed

**Review by jongiddy — APPROVED** [review]
